import { add, sub } from 'date-fns';
import { _mock } from './_mock';

// ----------------------------------------------------------------------

export const _bankingAccounts = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    type: 'checking',
    status: 'active',
    balance: 12500.75,
    currency: 'USD',
    accountNumber: '**** **** **** 1234',
    routingNumber: '123456789',
    name: 'Primary Checking',
    createdAt: sub(new Date(), { days: 365 }),
    updatedAt: new Date(),
    isDefault: true,
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    type: 'savings',
    status: 'active',
    balance: 35750.20,
    currency: 'USD',
    accountNumber: '**** **** **** 5678',
    name: 'Emergency Fund',
    createdAt: sub(new Date(), { days: 300 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    type: 'investment',
    status: 'active',
    balance: 78200.45,
    currency: 'USD',
    accountNumber: '**** **** **** 9012',
    name: 'Investment Portfolio',
    createdAt: sub(new Date(), { days: 200 }),
    updatedAt: new Date(),
  },
];

export const _bankingCards = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    cardType: 'visa',
    cardNumber: '**** **** **** 1234',
    cardHolder: _mock.fullName(1),
    cardValid: '12/25',
    isVirtual: false,
    isActive: true,
    dailyLimit: 5000,
    monthlyLimit: 20000,
    createdAt: sub(new Date(), { days: 365 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    cardType: 'mastercard',
    cardNumber: '**** **** **** 5678',
    cardHolder: _mock.fullName(1),
    cardValid: '06/26',
    isVirtual: true,
    isActive: true,
    dailyLimit: 2000,
    monthlyLimit: 10000,
    createdAt: sub(new Date(), { days: 180 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    accountId: _mock.id(2),
    cardType: 'amex',
    cardNumber: '**** **** **** 9012',
    cardHolder: _mock.fullName(1),
    cardValid: '09/27',
    isVirtual: false,
    isActive: true,
    dailyLimit: 10000,
    monthlyLimit: 50000,
    createdAt: sub(new Date(), { days: 90 }),
    updatedAt: new Date(),
  },
];

export const _bankingTransactions = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    type: 'income',
    amount: 5250.00,
    currency: 'USD',
    description: 'Salary Payment',
    category: 'Income',
    status: 'completed',
    recipientName: _mock.fullName(1),
    date: sub(new Date(), { days: 1 }),
    createdAt: sub(new Date(), { days: 1 }),
    updatedAt: sub(new Date(), { days: 1 }),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    type: 'expense',
    amount: 1250.00,
    currency: 'USD',
    description: 'Rent Payment',
    category: 'Housing',
    status: 'completed',
    recipientName: 'Apartment LLC',
    date: sub(new Date(), { days: 2 }),
    createdAt: sub(new Date(), { days: 2 }),
    updatedAt: sub(new Date(), { days: 2 }),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    type: 'expense',
    amount: 85.20,
    currency: 'USD',
    description: 'Grocery Shopping',
    category: 'Food & Dining',
    status: 'completed',
    recipientName: 'Whole Foods',
    date: sub(new Date(), { days: 3 }),
    createdAt: sub(new Date(), { days: 3 }),
    updatedAt: sub(new Date(), { days: 3 }),
  },
  {
    id: _mock.id(4),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    type: 'expense',
    amount: 45.75,
    currency: 'USD',
    description: 'Gas Station',
    category: 'Transportation',
    status: 'completed',
    recipientName: 'Shell Gas',
    date: sub(new Date(), { days: 4 }),
    createdAt: sub(new Date(), { days: 4 }),
    updatedAt: sub(new Date(), { days: 4 }),
  },
  {
    id: _mock.id(5),
    userId: _mock.id(1),
    accountId: _mock.id(1),
    type: 'transfer',
    amount: 1000.00,
    currency: 'USD',
    description: 'Transfer to Savings',
    category: 'Transfer',
    status: 'completed',
    recipientAccountId: _mock.id(2),
    date: sub(new Date(), { days: 5 }),
    createdAt: sub(new Date(), { days: 5 }),
    updatedAt: sub(new Date(), { days: 5 }),
  },
];

export const _bankingContacts = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    name: _mock.fullName(2),
    email: _mock.email(2),
    accountNumber: '**** **** **** 3456',
    bankName: 'Chase Bank',
    avatarUrl: _mock.image.avatar(2),
    isFavorite: true,
    createdAt: sub(new Date(), { days: 30 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    name: _mock.fullName(3),
    email: _mock.email(3),
    accountNumber: '**** **** **** 7890',
    bankName: 'Wells Fargo',
    avatarUrl: _mock.image.avatar(3),
    isFavorite: true,
    createdAt: sub(new Date(), { days: 25 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    name: _mock.fullName(4),
    email: _mock.email(4),
    accountNumber: '**** **** **** 2345',
    bankName: 'Bank of America',
    avatarUrl: _mock.image.avatar(4),
    isFavorite: false,
    createdAt: sub(new Date(), { days: 20 }),
    updatedAt: new Date(),
  },
];

export const _bankingBudgets = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    category: 'Housing',
    amount: 1500.00,
    currency: 'USD',
    period: 'monthly',
    startDate: sub(new Date(), { months: 1 }),
    spent: 1250.00,
    remaining: 250.00,
    createdAt: sub(new Date(), { months: 1 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    category: 'Food & Dining',
    amount: 600.00,
    currency: 'USD',
    period: 'monthly',
    startDate: sub(new Date(), { months: 1 }),
    spent: 423.45,
    remaining: 176.55,
    createdAt: sub(new Date(), { months: 1 }),
    updatedAt: new Date(),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    category: 'Transportation',
    amount: 300.00,
    currency: 'USD',
    period: 'monthly',
    startDate: sub(new Date(), { months: 1 }),
    spent: 275.50,
    remaining: 24.50,
    createdAt: sub(new Date(), { months: 1 }),
    updatedAt: new Date(),
  },
];

export const _bankingNotifications = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    title: 'Low Balance Alert',
    message: 'Your account balance is below your set threshold of $500',
    type: 'alert',
    isRead: false,
    createdAt: sub(new Date(), { hours: 1 }),
    updatedAt: sub(new Date(), { hours: 1 }),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    title: 'Transfer Successful',
    message: 'Your transfer of $1,000 to Savings Account has been completed',
    type: 'info',
    isRead: false,
    createdAt: sub(new Date(), { hours: 5 }),
    updatedAt: sub(new Date(), { hours: 5 }),
  },
  {
    id: _mock.id(3),
    userId: _mock.id(1),
    title: 'New Card Activated',
    message: 'Your new virtual card has been successfully activated',
    type: 'info',
    isRead: true,
    createdAt: sub(new Date(), { days: 1 }),
    updatedAt: sub(new Date(), { days: 1 }),
  },
];

export const _financialAccounts = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    stripeFinancialAccountId: 'fa_123456789',
    status: 'active',
    balance: 15750.25,
    currency: 'USD',
    createdAt: sub(new Date(), { months: 3 }),
    updatedAt: new Date(),
  }
];

export const _cashBackRewards = [
  {
    id: _mock.id(1),
    userId: _mock.id(1),
    transactionId: _mock.id(2),
    amount: 12.50,
    percentage: 1.0,
    category: 'Housing',
    status: 'credited',
    creditedAt: sub(new Date(), { days: 2 }),
    createdAt: sub(new Date(), { days: 2 }),
    updatedAt: sub(new Date(), { days: 2 }),
  },
  {
    id: _mock.id(2),
    userId: _mock.id(1),
    transactionId: _mock.id(3),
    amount: 4.26,
    percentage: 5.0,
    category: 'Food & Dining',
    status: 'credited',
    creditedAt: sub(new Date(), { days: 3 }),
    createdAt: sub(new Date(), { days: 3 }),
    updatedAt: sub(new Date(), { days: 3 }),
  },
];

export const _bankingSettings = {
  id: _mock.id(1),
  userId: _mock.id(1),
  overdraftProtection: true,
  lowBalanceAlert: true,
  lowBalanceThreshold: 500,
  twoFactorAuth: true,
  notificationPreferences: {
    transactions: true,
    bills: true,
    rewards: true,
    security: true,
  },
  createdAt: sub(new Date(), { years: 1 }),
  updatedAt: new Date(),
}; 